CREATE TABLE IF NOT EXISTS notes (
  id SERIAL PRIMARY KEY,
  msg TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO notes(msg) VALUES ('hello from Di3 - SQL container');
